version: '3'
services:
      
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=1y5h8j
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth-db
    ports:
      - 5432:5432

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=1y5h8j
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product-db
    ports:
      - 5433:5432

  sales-db:
    image: tutum/mongodb
    container_name: sales-db
    restart: always
    environment:
      - AUTH=no
    ports:
      - '27017:27017'
      - '28017:28017'