server:
  port: 8081
  servlet:
    context-path: /product

spring:
  application:
    name: product

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/registry/eureka

security:
  jwt:
    token:
      secret-key: microservices_application_test_dev

client:
  service:
    sales:
      url: http://localhost:8082/sales/sales

rabbit:
  exchange:
    product: product.topic

  routingkey:
    product-stock: product.stock-update.routingkey
    product-sales-confirmation: product-sales-confirmation.routingkey

  queue:
    product-stock: product.stock-update.queue
    product-sales-confirmation: product-sales-confirmation.queue