INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (2, 'Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (3, 'Movies');

INSERT INTO SUPPLIER (ID, NAME, EIN_CNPJ) VALUES (1, 'Amazon', '515151165');
INSERT INTO SUPPLIER (ID, NAME, EIN_CNPJ) VALUES (2, 'Ebay', '156156181856');
INSERT INTO SUPPLIER (ID, NAME, EIN_CNPJ) VALUES (3, 'Panini', '444886664');

INSERT INTO PRODUCT (ID, DESCRIPTION, PRICE, QUANTITY_AVAILABLE, FK_CATEGORY, FK_SUPPLIER) VALUES (1, 'Man of Steel', 19.9, 3, 1, 1);
INSERT INTO PRODUCT (ID, DESCRIPTION, PRICE, QUANTITY_AVAILABLE, FK_CATEGORY, FK_SUPPLIER) VALUES (2, 'Spider-Man 2', 14.9, 1, 3, 2);
INSERT INTO PRODUCT (ID, DESCRIPTION, PRICE, QUANTITY_AVAILABLE, FK_CATEGORY, FK_SUPPLIER) VALUES (3, 'Harry Potter', 25.9, 2, 2, 2);
INSERT INTO PRODUCT (ID, DESCRIPTION, PRICE, QUANTITY_AVAILABLE, FK_CATEGORY, FK_SUPPLIER) VALUES (4, 'Liga da Justiça 01', 5.99, 4, 1, 3);