server:
  port: 3000

spring:
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/registry/eureka

zuul:
  prefix: /api
  ignored-services: "*"

  routes:

    sales:
      path: /sales/**
      service-id: sales
      strip-prefix: false
      custom-sensitive-headers: true

    product:
      path: /product/**
      service-id: product
      strip-prefix: false
      custom-sensitive-headers: true

    auth:
      path: /auth/**
      service-id: auth
      strip-prefix: false
      custom-sensitive-headers: true