server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/registry/eureka

ribbon:
  eureka:
    enabled: true

zuul:
  prefix: /api
  ignored-services: "*"

  routes:
    sales:
      custom-sensitive-headers: true
      url: ${SALES_URL}

    product:
      custom-sensitive-headers: true
      url: ${PRODUCT_URL}

    auth:
      custom-sensitive-headers: true
      url: ${AUTH_URL}
