server:
  port: 3000

spring:
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/registry/eureka

ribbon:
  eureka:
    enabled: true

zuul:
  prefix: /api
  ignored-services: "*"

  routes:
    sales:
      custom-sensitive-headers: true
      url: http://localhost:8082/sales/

    product:
      custom-sensitive-headers: true
      url: http://localhost:8081/product/

    auth:
      custom-sensitive-headers: true
      url: http://localhost:8080/auth/
